# Generated by Django 4.0.4 on 2022-06-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_alter_phone_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(db_column=models.CharField(max_length=100), max_length=100),
        ),
    ]
